FROM golang:1.22.5-alpine AS builder

WORKDIR /usr/src/app

COPY . .

RUN go mod init rodrigobunhak/rocks

RUN go build

FROM scratch

WORKDIR /app

COPY --from=builder /usr/src/app .

ENTRYPOINT [ "./rocks" ]